### ISSUE TITLE
ibv_td(thread domain)

### ISSUE THREAD

**Issue by minxinhao** [madsys-dev/smart#4]
Ibv_td seems to do the same job as smart, which was integrated in rdma-core in 2017.
https://patchwork.kernel.org/project/linux-rdma/patch/1510522903-6838-2-git-send-email-yishaih@mellanox.com/

**Comment by alogfans** [comment]
`ibv_alloc_td()` cannot meet our needs. Although it allows users to allocate resources in a per-threaded manner, he/she also needs to call `ibv_alloc_parent_domain()` to get `ibv_pd` objects for each thread. This still makes duplicated memory regions / memory windows like per-context policy mentioned in this paper.
